info:
  app:
    version: '@project.version@'

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  metrics:
    tags:
      application: creditinstitute
    distribution:
      percentiles:
        all: 0.5, 0.75, 0.95, 0.98, 0.99, 0.999, 1.0
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

trace: false
 
opentracing:
  jaeger:
    service-name: creditinstitute
    enabled: ${T2_JAEGER_ENABLED}
    udp-sender:
      host: ${T2_JAEGER_HOST}

