management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
    health:
      show-details: always
  metrics:
    tags:
      application: creditinstitute
    distribution:
      percentiles:
        all: 0.5, 0.75, 0.95, 0.98, 0.99, 0.999, 1.0
  health:
    probes:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true
      
trace: false
 
opentracing:
  jaeger:
    service-name: creditinstitute
    enabled: TRUE
    udp-sender:
      host: ${JAEGER_HOST}

