name: test
on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
    - name: check out paymentprovider
      uses: actions/checkout@v2
    - name: set up jdk
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: verify paymentprovider
      run: mvn clean verify
